project_id = "dljnlqznteqxszbxdelw"

[functions.import-products]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.send-to-telegram]
verify_jwt = false

[functions.notify-order-status]
verify_jwt = false

[functions.check-abandoned-carts]
verify_jwt = false

[functions.check-inventory]
verify_jwt = false

[functions.payfast-notify]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false
